spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sweep_order?characterEncoding=utf-8&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=CTT
    username: root
    password: z123456
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 9000
  servlet:
    context-path: /
